# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mneme_v1_pb2 as mneme__v1__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mneme_v1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MnemeStub:
    """Mneme is the core memory-operation service. Every method corresponds to a
    stable operation in the mneme.memory.v1-draft contract.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommitMemory = channel.unary_unary(
                '/mneme.v1.Mneme/CommitMemory',
                request_serializer=mneme__v1__pb2.CommitMemoryRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.CommitMemoryResponse.FromString,
                _registered_method=True)
        self.AddEpisode = channel.unary_unary(
                '/mneme.v1.Mneme/AddEpisode',
                request_serializer=mneme__v1__pb2.AddEpisodeRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.AddEpisodeResponse.FromString,
                _registered_method=True)
        self.AddFact = channel.unary_unary(
                '/mneme.v1.Mneme/AddFact',
                request_serializer=mneme__v1__pb2.AddFactRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.AddFactResponse.FromString,
                _registered_method=True)
        self.InvalidateFact = channel.unary_unary(
                '/mneme.v1.Mneme/InvalidateFact',
                request_serializer=mneme__v1__pb2.InvalidateFactRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.InvalidateFactResponse.FromString,
                _registered_method=True)
        self.UpsertSubject = channel.unary_unary(
                '/mneme.v1.Mneme/UpsertSubject',
                request_serializer=mneme__v1__pb2.UpsertSubjectRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.UpsertSubjectResponse.FromString,
                _registered_method=True)
        self.UpsertEntity = channel.unary_unary(
                '/mneme.v1.Mneme/UpsertEntity',
                request_serializer=mneme__v1__pb2.UpsertEntityRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.UpsertEntityResponse.FromString,
                _registered_method=True)
        self.SearchMemory = channel.unary_unary(
                '/mneme.v1.Mneme/SearchMemory',
                request_serializer=mneme__v1__pb2.SearchMemoryRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.SearchMemoryResponse.FromString,
                _registered_method=True)
        self.QueryMemories = channel.unary_unary(
                '/mneme.v1.Mneme/QueryMemories',
                request_serializer=mneme__v1__pb2.QueryMemoriesRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.QueryMemoriesResponse.FromString,
                _registered_method=True)
        self.QueryFacts = channel.unary_unary(
                '/mneme.v1.Mneme/QueryFacts',
                request_serializer=mneme__v1__pb2.QueryFactsRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.QueryFactsResponse.FromString,
                _registered_method=True)
        self.ResolveEntity = channel.unary_unary(
                '/mneme.v1.Mneme/ResolveEntity',
                request_serializer=mneme__v1__pb2.ResolveEntityRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.ResolveEntityResponse.FromString,
                _registered_method=True)
        self.ResolveEntityExplained = channel.unary_unary(
                '/mneme.v1.Mneme/ResolveEntityExplained',
                request_serializer=mneme__v1__pb2.ResolveEntityExplainedRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.ResolveEntityExplainedResponse.FromString,
                _registered_method=True)
        self.ExtractEpisode = channel.unary_unary(
                '/mneme.v1.Mneme/ExtractEpisode',
                request_serializer=mneme__v1__pb2.ExtractEpisodeRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.ExtractEpisodeResponse.FromString,
                _registered_method=True)
        self.CreateBranch = channel.unary_unary(
                '/mneme.v1.Mneme/CreateBranch',
                request_serializer=mneme__v1__pb2.CreateBranchRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.CreateBranchResponse.FromString,
                _registered_method=True)
        self.MergeBranch = channel.unary_unary(
                '/mneme.v1.Mneme/MergeBranch',
                request_serializer=mneme__v1__pb2.MergeBranchRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.MergeBranchResponse.FromString,
                _registered_method=True)
        self.ListBranches = channel.unary_unary(
                '/mneme.v1.Mneme/ListBranches',
                request_serializer=mneme__v1__pb2.ListBranchesRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.ListBranchesResponse.FromString,
                _registered_method=True)
        self.SetRetentionState = channel.unary_unary(
                '/mneme.v1.Mneme/SetRetentionState',
                request_serializer=mneme__v1__pb2.SetRetentionStateRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.SetRetentionStateResponse.FromString,
                _registered_method=True)
        self.VerifyCommitIndex = channel.unary_unary(
                '/mneme.v1.Mneme/VerifyCommitIndex',
                request_serializer=mneme__v1__pb2.VerifyCommitIndexRequest.SerializeToString,
                response_deserializer=mneme__v1__pb2.VerifyCommitIndexResponse.FromString,
                _registered_method=True)


class MnemeServicer:
    """Mneme is the core memory-operation service. Every method corresponds to a
    stable operation in the mneme.memory.v1-draft contract.

    """

    def CommitMemory(self, request, context):
        """--- typed writes ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateFact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertSubject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemory(self, request, context):
        """--- queries ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryFacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveEntity(self, request, context):
        """--- resolution ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveEntityExplained(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEpisode(self, request, context):
        """--- extraction ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBranch(self, request, context):
        """--- branching ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MergeBranch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBranches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRetentionState(self, request, context):
        """--- maintenance ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyCommitIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MnemeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommitMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitMemory,
                    request_deserializer=mneme__v1__pb2.CommitMemoryRequest.FromString,
                    response_serializer=mneme__v1__pb2.CommitMemoryResponse.SerializeToString,
            ),
            'AddEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEpisode,
                    request_deserializer=mneme__v1__pb2.AddEpisodeRequest.FromString,
                    response_serializer=mneme__v1__pb2.AddEpisodeResponse.SerializeToString,
            ),
            'AddFact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFact,
                    request_deserializer=mneme__v1__pb2.AddFactRequest.FromString,
                    response_serializer=mneme__v1__pb2.AddFactResponse.SerializeToString,
            ),
            'InvalidateFact': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateFact,
                    request_deserializer=mneme__v1__pb2.InvalidateFactRequest.FromString,
                    response_serializer=mneme__v1__pb2.InvalidateFactResponse.SerializeToString,
            ),
            'UpsertSubject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertSubject,
                    request_deserializer=mneme__v1__pb2.UpsertSubjectRequest.FromString,
                    response_serializer=mneme__v1__pb2.UpsertSubjectResponse.SerializeToString,
            ),
            'UpsertEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertEntity,
                    request_deserializer=mneme__v1__pb2.UpsertEntityRequest.FromString,
                    response_serializer=mneme__v1__pb2.UpsertEntityResponse.SerializeToString,
            ),
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=mneme__v1__pb2.SearchMemoryRequest.FromString,
                    response_serializer=mneme__v1__pb2.SearchMemoryResponse.SerializeToString,
            ),
            'QueryMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMemories,
                    request_deserializer=mneme__v1__pb2.QueryMemoriesRequest.FromString,
                    response_serializer=mneme__v1__pb2.QueryMemoriesResponse.SerializeToString,
            ),
            'QueryFacts': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFacts,
                    request_deserializer=mneme__v1__pb2.QueryFactsRequest.FromString,
                    response_serializer=mneme__v1__pb2.QueryFactsResponse.SerializeToString,
            ),
            'ResolveEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveEntity,
                    request_deserializer=mneme__v1__pb2.ResolveEntityRequest.FromString,
                    response_serializer=mneme__v1__pb2.ResolveEntityResponse.SerializeToString,
            ),
            'ResolveEntityExplained': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveEntityExplained,
                    request_deserializer=mneme__v1__pb2.ResolveEntityExplainedRequest.FromString,
                    response_serializer=mneme__v1__pb2.ResolveEntityExplainedResponse.SerializeToString,
            ),
            'ExtractEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEpisode,
                    request_deserializer=mneme__v1__pb2.ExtractEpisodeRequest.FromString,
                    response_serializer=mneme__v1__pb2.ExtractEpisodeResponse.SerializeToString,
            ),
            'CreateBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBranch,
                    request_deserializer=mneme__v1__pb2.CreateBranchRequest.FromString,
                    response_serializer=mneme__v1__pb2.CreateBranchResponse.SerializeToString,
            ),
            'MergeBranch': grpc.unary_unary_rpc_method_handler(
                    servicer.MergeBranch,
                    request_deserializer=mneme__v1__pb2.MergeBranchRequest.FromString,
                    response_serializer=mneme__v1__pb2.MergeBranchResponse.SerializeToString,
            ),
            'ListBranches': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBranches,
                    request_deserializer=mneme__v1__pb2.ListBranchesRequest.FromString,
                    response_serializer=mneme__v1__pb2.ListBranchesResponse.SerializeToString,
            ),
            'SetRetentionState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRetentionState,
                    request_deserializer=mneme__v1__pb2.SetRetentionStateRequest.FromString,
                    response_serializer=mneme__v1__pb2.SetRetentionStateResponse.SerializeToString,
            ),
            'VerifyCommitIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyCommitIndex,
                    request_deserializer=mneme__v1__pb2.VerifyCommitIndexRequest.FromString,
                    response_serializer=mneme__v1__pb2.VerifyCommitIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mneme.v1.Mneme', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mneme.v1.Mneme', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mneme:
    """Mneme is the core memory-operation service. Every method corresponds to a
    stable operation in the mneme.memory.v1-draft contract.

    """

    @staticmethod
    def CommitMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/CommitMemory',
            mneme__v1__pb2.CommitMemoryRequest.SerializeToString,
            mneme__v1__pb2.CommitMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/AddEpisode',
            mneme__v1__pb2.AddEpisodeRequest.SerializeToString,
            mneme__v1__pb2.AddEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/AddFact',
            mneme__v1__pb2.AddFactRequest.SerializeToString,
            mneme__v1__pb2.AddFactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateFact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/InvalidateFact',
            mneme__v1__pb2.InvalidateFactRequest.SerializeToString,
            mneme__v1__pb2.InvalidateFactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertSubject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/UpsertSubject',
            mneme__v1__pb2.UpsertSubjectRequest.SerializeToString,
            mneme__v1__pb2.UpsertSubjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/UpsertEntity',
            mneme__v1__pb2.UpsertEntityRequest.SerializeToString,
            mneme__v1__pb2.UpsertEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/SearchMemory',
            mneme__v1__pb2.SearchMemoryRequest.SerializeToString,
            mneme__v1__pb2.SearchMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/QueryMemories',
            mneme__v1__pb2.QueryMemoriesRequest.SerializeToString,
            mneme__v1__pb2.QueryMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryFacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/QueryFacts',
            mneme__v1__pb2.QueryFactsRequest.SerializeToString,
            mneme__v1__pb2.QueryFactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/ResolveEntity',
            mneme__v1__pb2.ResolveEntityRequest.SerializeToString,
            mneme__v1__pb2.ResolveEntityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveEntityExplained(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/ResolveEntityExplained',
            mneme__v1__pb2.ResolveEntityExplainedRequest.SerializeToString,
            mneme__v1__pb2.ResolveEntityExplainedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/ExtractEpisode',
            mneme__v1__pb2.ExtractEpisodeRequest.SerializeToString,
            mneme__v1__pb2.ExtractEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/CreateBranch',
            mneme__v1__pb2.CreateBranchRequest.SerializeToString,
            mneme__v1__pb2.CreateBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MergeBranch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/MergeBranch',
            mneme__v1__pb2.MergeBranchRequest.SerializeToString,
            mneme__v1__pb2.MergeBranchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBranches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/ListBranches',
            mneme__v1__pb2.ListBranchesRequest.SerializeToString,
            mneme__v1__pb2.ListBranchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetRetentionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/SetRetentionState',
            mneme__v1__pb2.SetRetentionStateRequest.SerializeToString,
            mneme__v1__pb2.SetRetentionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyCommitIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mneme.v1.Mneme/VerifyCommitIndex',
            mneme__v1__pb2.VerifyCommitIndexRequest.SerializeToString,
            mneme__v1__pb2.VerifyCommitIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
